services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    volumes:
      - ./django:/app
    networks:
      - mynetwork
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    depends_on:
      - django

networks:
  mynetwork:
    driver: bridge  # You can specify other drivers if needed
